# Generated by Django 3.1.7 on 2021-03-18 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_uploadfile_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='uploaded_at',
        ),
    ]
