# Generated by Django 3.1.7 on 2021-03-19 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_uploadfile_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('avg_col', models.CharField(max_length=100)),
                ('num_coins', models.IntegerField(default=0)),
                ('sum_coins', models.IntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.uploadfile')),
            ],
        ),
    ]
