# Generated by Django 3.1.7 on 2021-03-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_fileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
