# Generated by Django 3.1.7 on 2021-03-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210319_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.uploadfile'),
        ),
    ]
