# Generated by Django 3.1.7 on 2021-03-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210319_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
