# Generated by Django 3.1.7 on 2021-03-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_fileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='num_of_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='sum_of_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
